name: plugin-utilities-store
org: sapphire
install: true
packagePath: packages/utilities-store
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/plugins
gitHostVariant: github
