name: plugin-scheduled-tasks
org: sapphire
install: true
packagePath: packages/scheduled-tasks
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/plugins
gitHostVariant: github
