name: plugin-pattern-commands
org: sapphire
install: true
packagePath: packages/pattern-commands
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/plugins
gitHostVariant: github
