name: plugin-api
org: sapphire
install: true
packagePath: packages/api
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/plugins
gitHostVariant: github
