name: plugin-hmr
org: sapphire
install: true
packagePath: packages/hmr
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/plugins
gitHostVariant: github
