name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - '**'

concurrency:
  group: ${{ github.workspace }}|${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docgen:
    uses: sapphiredev/.github/.github/workflows/reusable-documentation-docgen.yml@main
    with:
      mono-repo: true

  upload:
    needs: docgen
    uses: sapphiredev/.github/.github/workflows/reusable-documentation-upload.yml@main
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        package:
          - api
          - editable-commands
          - hmr
          - i18next
          - logger
          - pattern-commands
          - scheduled-tasks
          - subcommands
          - utilities-store
    with:
      project-name: plugins
      mono-repo: true
      name: ${{ needs.docgen.outputs.NAME }}
      type: ${{ needs.docgen.outputs.TYPE }}
      sha: ${{ needs.docgen.outputs.SHA }}
      package: ${{ matrix.package }}
      artifact-id: ${{ needs.docgen.outputs.artifact-id }}
    secrets:
      SKYRA_TOKEN: ${{ secrets.SKYRA_TOKEN }}
